### ISSUE TITLE
compile issue when trying planetary simulation

### ISSUE THREAD

**Issue by JingyaoDOU** [SWIFTSIM/swiftsim#16]
I'm trying to run the /Planetary/EarthImpact example provided and I have some issues trying to get swift compile. 
```
./configure --with-hydro=planetary --with-equation-of-state=planetary --with-hdf5=/path/to/hdf5
make -j8 check 
```
and  I got the error
```
In file included from testRiemannTRRS.c:26:0:
../src/riemann/riemann_trrs.h:37:2: error: #error "The TRRS Riemann solver currently only supports an ideal gas equation of state.
 Either select this equation of state, or try using another Riemann solver!"
```
The code was run on a `Centos 7` Linux distribution with `Intel Xeon` CPU. The hdf5 libraries is `hdf5-1.12.1-Linux-centos7-x86_64-gcc485`.

could you please help?

**Comment by bwvdnbro** [comment]
That looks like an issue with one of the unit tests. Could you compile without the `check` (so just `make -j8`). `make check` only compiles and runs the unit tests, it does not compile the code.

**Comment by JingyaoDOU** [comment]
Hi Bert, it works this time, thank you for the advice!

**Comment by MatthieuSchaller** [comment]
Great.

This falls definitely at the very bottom of the todo-list but we should fix the checks to not break in this case.
Clearly planetary + gizmo is a no-go.
