### ISSUE TITLE
HM80 ice sitting on HM80 hydrogen helium in giant impact simulations

### ISSUE THREAD

**Issue by joe637** [SWIFTSIM/swiftsim#28]
I am currently running giant impact simulations of an icy object impacting on a Uranus-like ice giant planet using the equations of state of Hubbard and Macfarlane (1980). However, whenever I try to run this in SWIFT, it seems to leave a layer of the impactor ice on top of the hydrogen helium atmosphere of the ice giant. This clearly isn't a physical result. I have checked the mass of the impactor and target particles and they are both similar enough such that this shouldn't be a problem, but it still seems to be happening. Do you have any suggestions on what I could change to remove this problem

https://user-images.githubusercontent.com/88051094/157776973-ff0e5771-6321-4277-9bce-6a855f21db4f.mp4

**Comment by jkeger** [comment]
Hi Joe, I don't remember all the details but I assume this is the issue we emailed about at the time, which we decided wasn't an actual concern after all?
