### ISSUE TITLE
Small mod required for build

### ISSUE THREAD

**Issue by PhilRid** [SWIFTSIM/swiftsim#5]
Hi,

Attached is a file [cycle.h.patch.txt](https://github.com/SWIFTSIM/swiftsim/files/2398060/cycle.h.patch.txt) which can be used to patch src/cycle.h so that SWIFT builds on Arm.

Please try `patch src/cycle.h -i cycle.h.patch.txt -o cycle.h`

this should create a new file `cycle.h` which should replace `src/cycle.h`

Thanks.

**Comment by MatthieuSchaller** [comment]
Thanks! 

cycle.h is taken directly from FFTW. What ARM chip are you considering here?

**Comment by JBorrow** [comment]
This should permanently fix the issues that I was having building on the test system at Leicester(?) for the new Cray machines (with the Cavium ThunderX2s).

**Comment by MatthieuSchaller** [comment]
I have pushed that patch to the master branch. It will appear online with our daily push. 

I have also contacted the upstream developers too see whether they'd be interested in patching their version as well. 

Thanks!

**Comment by PhilRid** [comment]
Just looking at the source for src/cycle.h again, it looks like something went wrong with the patch.

Line 534 should be 

!defined(HAVE_TICK_COUNTER)

rather than 

!defined(HAVE_ARMV8_PMCCNTR_EL0) && !defined(HAAVE_TICK_COUNTER)

Thanks!

**Comment by MatthieuSchaller** [comment]
Indeed! Not sure what happened there. Should have checked the result instead of just trusting the merge.

Anyway, I have just pushed the correct line to the master branch.
