### ISSUE TITLE
Uninitialised pointer in src/proxy.c?

### ISSUE THREAD

**Issue by PhilRid** [SWIFTSIM/swiftsim#6]
Hi,

I was just trying to build with a Clang based compiler and noticed the following

```
proxy.c:111:7: error: variable 'cids_in' is used uninitialized whenever '||' condition is true [-Werror,-Wsometimes-uninitialized]
  if ((reqs_in = (MPI_Request *)malloc(sizeof(MPI_Request) *
```

In src/proxy.c, initialising the pointer `cids_in` fixes it, i.e.

`int *cids_in=NULL;`

Thanks.

**Comment by JBorrow** [comment]
Thanks for the report! We actually fixed this issue yesterday. Updating to the latest master (from the GitLab, not the GitHub mirror) should fix this.
